services:
    laravel:
        image: shoppingapp:latest
        build:
            context: .
        command: bash -c "npm run build && php artisan serve --host 0.0.0.0"
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - /var/www/html
    db:
        image: mysql:9.0.1
        env_file:
            - .env
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: laravel
            MYSQL_USERNAME: root
            MYSQL_PASSWORD:
        ports:
            - "3306:3306"
